<CustButton@Button>:
    font_size: 32
    color: 0,0,0,1 #rgb,alpha
    size: 150,50 #wide, deep(height)
    background_normal: ''
    background_color: 0.88,0.88,0.88, 1.0
    
<CustomWidget>:
    CustButton:
        text: "Random"
        pos: root.x, 200
        
    CustButton:
        text: "Buttons"
        pos: 200, root.y
        
    CustButton:
        text: "Random2"
        pos: 200,400